import { env } from "../config/env";
import { prisma } from "../config/database";

const RESEND_API = "https://api.resend.com/emails";

function serialize(obj: any): string {
  return JSON.stringify(obj);
}

function deserialize<T>(str: string | null | undefined, fallback: T): T {
  if (!str) return fallback;
  try {
    return JSON.parse(str);
  } catch {
    return fallback;
  }
}

export async function sendAnalysisReport(analysisId: string, userId: string, toEmail: string) {
  const analysis = await prisma.analysis.findFirst({
    where: { id: analysisId, userId },
    include: {
      resume: { select: { originalName: true } },
    },
  });

  if (!analysis) {
    throw new Error("Analysis not found");
  }

  const strengths = deserialize<string[]>(analysis.strengths, []);
  const weaknesses = deserialize<string[]>(analysis.weaknesses, []);
  const recommendations = deserialize<string[]>(analysis.recommendations, []);
  const atsTips = deserialize<string[]>(analysis.atsTips, []);

  const html = `
<!DOCTYPE html>
<html>
<head><meta charset="utf-8"></head>
<body style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px;">
  <div style="text-align: center; margin-bottom: 30px;">
    <h1 style="color: #1E293B; font-size: 24px;">Resume Analysis Report</h1>
    <p style="color: #64748B;">${analysis.resume.originalName}</p>
  </div>

  <div style="background: #F8FAFC; border-radius: 12px; padding: 24px; margin-bottom: 20px;">
    <h2 style="color: #1E293B; font-size: 18px; margin-top: 0;">ATS Score: ${analysis.atsScore}/100</h2>
    <div style="display: flex; gap: 20px; margin-top: 16px;">
      <div style="flex: 1; text-align: center; padding: 12px; background: white; border-radius: 8px;">
        <p style="color: #64748B; font-size: 12px; margin: 0;">Grammar</p>
        <p style="font-size: 20px; font-weight: bold; color: ${analysis.grammarScore >= 70 ? "#22c55e" : "#CA492A"}; margin: 4px 0;">${analysis.grammarScore}%</p>
      </div>
      <div style="flex: 1; text-align: center; padding: 12px; background: white; border-radius: 8px;">
        <p style="color: #64748B; font-size: 12px; margin: 0;">Keywords</p>
        <p style="font-size: 20px; font-weight: bold; color: ${analysis.keywordScore >= 70 ? "#22c55e" : "#CA492A"}; margin: 4px 0;">${analysis.keywordScore}%</p>
      </div>
      <div style="flex: 1; text-align: center; padding: 12px; background: white; border-radius: 8px;">
        <p style="color: #64748B; font-size: 12px; margin: 0;">Rating</p>
        <p style="font-size: 20px; font-weight: bold; color: #2AC5CA; margin: 4px 0;">${analysis.overallRating}</p>
      </div>
    </div>
  </div>

  <div style="margin-bottom: 20px;">
    <h3 style="color: #1E293B;">Summary</h3>
    <p style="color: #475569; line-height: 1.6;">${analysis.summary}</p>
  </div>

  <div style="margin-bottom: 20px;">
    <h3 style="color: #1E293B;">Strengths</h3>
    <ul style="color: #475569; line-height: 1.8;">
      ${strengths.map((s: string) => `<li>${s}</li>`).join("")}
    </ul>
  </div>

  <div style="margin-bottom: 20px;">
    <h3 style="color: #1E293B;">Areas for Improvement</h3>
    <ul style="color: #475569; line-height: 1.8;">
      ${weaknesses.map((w: string) => `<li>${w}</li>`).join("")}
    </ul>
  </div>

  <div style="margin-bottom: 20px;">
    <h3 style="color: #1E293B;">Recommendations</h3>
    <ol style="color: #475569; line-height: 1.8;">
      ${recommendations.map((r: string) => `<li>${r}</li>`).join("")}
    </ol>
  </div>

  <div style="margin-bottom: 20px;">
    <h3 style="color: #1E293B;">ATS Tips</h3>
    <ul style="color: #475569; line-height: 1.8;">
      ${atsTips.map((t: string) => `<li>${t}</li>`).join("")}
    </ul>
  </div>

  <div style="border-top: 1px solid #E2E8F0; padding-top: 20px; text-align: center; color: #94A3B8; font-size: 12px;">
    <p>Generated by AI Resume Analyzer</p>
  </div>
</body>
</html>`;

  const res = await fetch(RESEND_API, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${env.RESEND_API_KEY}`,
    },
    body: JSON.stringify({
      from: env.RESEND_FROM_EMAIL,
      to: toEmail,
      subject: `Resume Analysis Report - ${analysis.resume.originalName}`,
      html,
    }),
  });

  if (!res.ok) {
    const err = await res.text();
    throw new Error(`Resend API error (${res.status}): ${err}`);
  }

  return await res.json();
}
